spring:
  application:
    name: JWTAuthentication
#settings of postgres
  datasource:
    url: jdbc:postgresql://localhost:5435/rent_db
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true
#Security
security:
  jwt:
    secret_key: 4eeab38d706831be4b36612ead768ef8182d1dd6f0e14e5dc934652e297fb16a
    access_token_expiration: 36000000 # 10 hours
    refresh_token_expiration: 252000000 # 7 days
